### PR TITLE
Fixes for newer Django/Python compatibility + Travis testing

### LINKED ISSUE #22: Python 3 compatibility
When running on Python 3.5, I got follwing error:
```
  File "/home/petr/soubory/programovani/Auto-mat/aklub/aklub/env/lib/python3.5/site-packages/admin_tools_stats/modules.py", line 22, in <module>
    from django.utils.encoding import force_unicode
ImportError: cannot import name 'force_unicode'
```

### PR DESCRIPTION
**Pull request by PetrDlouhy**
I have made several fixes so this project is able to run in newer Django and Python versions. This is ensured by Travis tests which run in Django 1.7-1.10 and Python 2.7,3.4
This fixes #22 

@areski After pulling this PR, You will need to activate Travis tests for your repository.

### CODE REVIEW

**Comment by areski** [comment]
Amazing job!

**Comment by areski** [comment]
go ahead and commit your names in https://github.com/areski/django-admin-tools-stats/blob/develop/CONTRIBUTORS

**Comment by areski** [comment]
Merged and I released 0.7 with your changes, thanks

**Comment by PetrDlouhy** [comment]
Thanks for quick merging

**Pull request merged**
